# Generated by Django 5.2.8 on 2025-11-17 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('outcomes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('QUIZ', 'Quiz'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('PROJECT', 'Project'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('weight_in_course', models.PositiveSmallIntegerField(help_text='Contribution to course grade in percent (0-100).')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum raw score (e.g. 100).')),
                ('date', models.DateField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['curriculum', 'type', 'name'],
                'unique_together': {('curriculum', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_assessment', models.PositiveSmallIntegerField(help_text='Percentage of this assessment that targets this LO (0-100).')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_mappings', to='assessments.assessment')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='outcomes.learningoutcome')),
            ],
            options={
                'verbose_name': 'Assessment → LO Mapping',
                'verbose_name_plural': 'Assessment → LO Mappings',
                'unique_together': {('assessment', 'learning_outcome')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Raw score achieved (0 - max_score).')),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Assessment Result',
                'verbose_name_plural': 'Student Assessment Results',
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
