# Generated by Django 5.2.8 on 2025-11-17 14:12

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentassessmentresult',
            unique_together={('assessment', 'student')},
        ),
        migrations.AddField(
            model_name='studentassessmentresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassessmentresult',
            name='raw_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Öğrencinin bu assessment'tan aldığı puan (örn. 85.5).", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentassessmentresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='studentassessmentresult',
            name='score',
        ),
    ]
