# Generated by Django 5.2.8 on 2025-11-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_studentassessmentresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassessmentresult',
            name='graded_at',
        ),
    ]
