# Generated by Django 5.2.8 on 2025-11-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_studentassessmentresult_graded_at'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "assesments_studentassessmentresult";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "assesments_assessmentlearningoutcome";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "assesments_assessment";',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
