# Generated by Django 5.2.8 on 2025-11-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('curriculum', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_program',
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty Member için sorumlu olduğu Faculty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='organizations.faculty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lecturer_curricula',
            field=models.ManyToManyField(blank=True, help_text='Lecturer için sorumlu olduğu Curriculum(lar)', related_name='lecturers', to='curriculum.curriculum'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lecturer_programs',
            field=models.ManyToManyField(blank=True, help_text='Lecturer için sorumlu olduğu Program(lar)', related_name='lecturers', to='organizations.program'),
        ),
    ]
