# Generated by Django 5.2.8 on 2025-11-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_student_program_customuser_faculty_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Student için kayıtlı olduğu program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='organizations.program'),
        ),
    ]
