# Generated by Django 5.2.8 on 2025-11-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_program'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='faculty',
            new_name='faculty_member_faculty',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='grade',
            new_name='student_grade',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='program',
            new_name='student_program',
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_faculty',
            field=models.ForeignKey(blank=True, help_text='Student için kayıtlı olduğu Faculty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='organizations.faculty'),
        ),
    ]
