# Generated by Django 5.2.8 on 2025-11-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='LO kodu (örn: LO1)', max_length=20)),
                ('short_title', models.CharField(help_text='Kısa başlık (örn: Temel kavramları açıklama)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detaylı açıklama')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Ders içi LO sıralaması')),
                ('active', models.BooleanField(default=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='curriculum.curriculum')),
            ],
            options={
                'ordering': ['curriculum', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='PO kodu (örn: PO1, PLO2...)', max_length=20)),
                ('short_title', models.CharField(help_text='Kısa başlık (örn: Problem çözme)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detaylı açıklama')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Listelerde sıralama için')),
                ('active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='organizations.program')),
            ],
            options={
                'ordering': ['program', 'order', 'code'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LearningOutcomeProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=0, help_text="This LO's contribution to this PO in percent (0–100).")),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_po_mappings', to='outcomes.learningoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_lo_mappings', to='outcomes.programoutcome')),
            ],
            options={
                'unique_together': {('learning_outcome', 'program_outcome')},
            },
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='program_outcomes',
            field=models.ManyToManyField(blank=True, related_name='learning_outcomes', through='outcomes.LearningOutcomeProgramOutcome', to='outcomes.programoutcome'),
        ),
        migrations.AlterUniqueTogether(
            name='learningoutcome',
            unique_together={('curriculum', 'code')},
        ),
    ]
