# Generated by Django 5.2.8 on 2025-11-17 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Dersin tipik alındığı sınıf (1,2,3,4).', null=True)),
                ('semester', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('YEARLONG', 'Year-long')], default='FALL', max_length=16)),
                ('ects', models.DecimalField(blank=True, decimal_places=1, help_text='ECTS / AKTS', max_digits=4, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=1, help_text='Yerel kredi', max_digits=4, null=True)),
                ('description', models.TextField(blank=True, help_text='Ders açıklaması')),
                ('lecturer', models.ForeignKey(blank=True, help_text='Dersin genel sorumlu öğretim üyesi (program bazında).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_curricula_assigned', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='organizations.program')),
                ('students', models.ManyToManyField(blank=True, help_text='Bu derse kayıtlı öğrenciler (otomatik atanır).', related_name='enrolled_curricula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['program', 'year', 'semester', 'code'],
                'unique_together': {('program', 'code')},
            },
        ),
    ]
